name: PHP-CI

on: [ push, pull_request ]

jobs:
    # 2nd run with cache + parallel
    coding_standards:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '7.4' ]
                actions:
                    # Until dependencies fixed
                    # - { name: ecs, coverage: none, run: composer check-ecs }
                    # - { name: rector, coverage: none, run: composer check-rector }

                    - { name: monorepo, coverage: none, run: composer check-monorepo }
                    - { name: composer, coverage: none, run: composer check-composer }
                    - { name: phpstan, coverage: none, run: composer check-phpstan }

        name: ${{ matrix.actions.name}} (${{ matrix.php }})

        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: ${{ matrix.actions.coverage }}

            -   uses: eonx-com/actions-composer-install@v1

            -   run: composer install --working-dir=.quality

            -   name: '[CI] Check ${{ matrix.actions.name }} [CI]'
                run: ${{ matrix.actions.run }}
                shell: bash

    security-checker:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '7.4' ]
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   uses: eonx-com/actions-composer-install@v1

            -   uses: eonx-com/actions-security-checker@v2
